version: '2'

services:
  db:
    build: ./postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ravintolat
      - POSTGRES_DB=ravintolat
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - '5432:5432'
  admin:
    image: dockage/phppgadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=db
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=ravintolat
volumes:
  db-data:
    driver: local
