const LOCATION_CHANGE = '@@router/LOCATION_CHANGE'

const USER_REGISTER = 'USER_REGISTER'
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

const USER_LOGIN = 'USER_LOGIN'
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

const USER_LOGIN_PROFILE = 'USER_LOGIN_PROFILE'
const USER_LOGIN_PROFILE_SUCCESS = 'USER_LOGIN_PROFILE_SUCCESS'
const USER_LOGIN_PROFILE_ERROR = 'USER_LOGIN_PROFILE_ERROR'

const USER_LOGOUT = 'USER_LOGOUT'
const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR'

const RESTAURANT_ADD = 'RESTAURANT_ADD'
const RESTAURANT_ADD_SUCCESS = 'RESTAURANT_ADD_SUCCESS'
const RESTAURANT_ADD_ERROR = 'RESTAURANT_ADD_ERROR'

const RESTAURANT_UPDATE = 'RESTAURANT_UPDATE'
const RESTAURANT_UPDATE_SUCCESS = 'RESTAURANT_UPDATE_SUCCESS'
const RESTAURANT_UPDATE_ERROR = 'RESTAURANT_UPDATE_ERROR'

const RESTAURANT_DELETE = 'RESTAURANT_DELETE'
const RESTAURANT_DELETE_SUCCESS = 'RESTAURANT_DELETE_SUCCESS'
const RESTAURANT_DELETE_ERROR = 'RESTAURANT_DELETE_ERROR'

const RESTAURANTS_GET_ALL = 'RESTAURANTS_GET_ALL'
const RESTAURANTS_GET_ALL_SUCCESS = 'RESTAURANTS_GET_ALL_SUCCESS'
const RESTAURANTS_GET_ALL_ERROR = 'RESTAURANTS_GET_ALL_ERROR'

const RESTAURANTS_GET = 'RESTAURANTS_GET'
const RESTAURANTS_GET_SUCCESS = 'RESTAURANTS_GET_SUCCESS'
const RESTAURANTS_GET_ERROR = 'RESTAURANTS_GET_ERROR'

const MESSAGE_ADD = 'MESSAGE_ADD'
const MESSAGE_CLEAR = 'MESSAGE_CLEAR'

const RESTAURANT_REVIEW_ADD = 'RESTAURANT_REVIEW_ADD'
const RESTAURANT_REVIEW_ADD_SUCCESS = 'RESTAURANT_REVIEW_ADD_SUCCESS'
const RESTAURANT_REVIEW_ADD_ERROR = 'RESTAURANT_REVIEW_ADD_ERROR'

const RESTAURANT_REVIEW_DELETE = 'RESTAURANT_REVIEW_DELETE'
const RESTAURANT_REVIEW_DELETE_SUCCESS = 'RESTAURANT_REVIEW_DELETE_SUCCESS'
const RESTAURANT_REVIEW_DELETE_ERROR = 'RESTAURANT_REVIEW_DELETE_ERROR'

const FEATURES_GET = 'FEATURES_GET'
const FEATURES_GET_SUCCESS = 'FEATURES_GET_SUCCESS'
const FEATURES_GET_ERROR = 'FEATURES_GET_ERROR'

const FEATURE_ADD = 'FEATURE_ADD'
const FEATURE_ADD_SUCCESS = 'FEATURE_ADD_SUCCESS'
const FEATURE_ADD_ERROR = 'FEATURE_ADD_ERROR'

const FEATURE_UPDATE = 'FEATURE_UPDATE'
const FEATURE_UPDATE_SUCCESS = 'FEATURE_UPDATE_SUCCESS'
const FEATURE_UPDATE_ERROR = 'FEATURE_UPDATE_ERROR'

const FEATURE_DELETE = 'FEATURE_DELETE'
const FEATURE_DELETE_SUCCESS = 'FEATURE_DELETE_SUCCESS'
const FEATURE_DELETE_ERROR = 'FEATURE_DELETE_ERROR'

export {
  LOCATION_CHANGE,
  USER_REGISTER,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_ERROR,
  USER_LOGIN,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_ERROR,
  USER_LOGIN_PROFILE,
  USER_LOGIN_PROFILE_SUCCESS,
  USER_LOGIN_PROFILE_ERROR,
  USER_LOGOUT,
  USER_LOGOUT_SUCCESS,
  USER_LOGOUT_ERROR,
  RESTAURANT_ADD,
  RESTAURANT_ADD_SUCCESS,
  RESTAURANT_ADD_ERROR,
  RESTAURANT_UPDATE,
  RESTAURANT_UPDATE_SUCCESS,
  RESTAURANT_UPDATE_ERROR,
  RESTAURANT_DELETE,
  RESTAURANT_DELETE_SUCCESS,
  RESTAURANT_DELETE_ERROR,
  RESTAURANTS_GET_ALL,
  RESTAURANTS_GET_ALL_SUCCESS,
  RESTAURANTS_GET_ALL_ERROR,
  RESTAURANTS_GET,
  RESTAURANTS_GET_SUCCESS,
  RESTAURANTS_GET_ERROR,
  MESSAGE_ADD,
  MESSAGE_CLEAR,
  RESTAURANT_REVIEW_ADD,
  RESTAURANT_REVIEW_ADD_SUCCESS,
  RESTAURANT_REVIEW_ADD_ERROR,
  RESTAURANT_REVIEW_DELETE,
  RESTAURANT_REVIEW_DELETE_SUCCESS,
  RESTAURANT_REVIEW_DELETE_ERROR,
  FEATURES_GET,
  FEATURES_GET_ERROR,
  FEATURES_GET_SUCCESS,
  FEATURE_ADD,
  FEATURE_ADD_SUCCESS,
  FEATURE_ADD_ERROR,
  FEATURE_UPDATE,
  FEATURE_UPDATE_ERROR,
  FEATURE_UPDATE_SUCCESS,
  FEATURE_DELETE,
  FEATURE_DELETE_ERROR,
  FEATURE_DELETE_SUCCESS,
}
