const LOCATION_CHANGE = '@@router/LOCATION_CHANGE'

const USER_REGISTER = 'USER_REGISTER'
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

const USER_LOGIN = 'USER_LOGIN'
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

const USER_LOGIN_PROFILE = 'USER_LOGIN_PROFILE'
const USER_LOGIN_PROFILE_SUCCESS = 'USER_LOGIN_PROFILE_SUCCESS'
const USER_LOGIN_PROFILE_ERROR = 'USER_LOGIN_PROFILE_ERROR'

const USER_LOGOUT = 'USER_LOGOUT'
const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR'

const RESTAURANT_ADD = 'RESTAURANT_ADD'
const RESTAURANT_ADD_SUCCESS = 'RESTAURANT_ADD_SUCCESS'
const RESTAURANT_ADD_ERROR = 'RESTAURANT_ADD_ERROR'

const MESSAGE_ADD = 'MESSAGE_ADD'
const MESSAGE_CLEAR = 'MESSAGE_CLEAR'

export {
  LOCATION_CHANGE,
  USER_REGISTER,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_ERROR,
  USER_LOGIN,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_ERROR,
  USER_LOGIN_PROFILE,
  USER_LOGIN_PROFILE_SUCCESS,
  USER_LOGIN_PROFILE_ERROR,
  USER_LOGOUT,
  USER_LOGOUT_SUCCESS,
  USER_LOGOUT_ERROR,
  RESTAURANT_ADD,
  RESTAURANT_ADD_SUCCESS,
  RESTAURANT_ADD_ERROR,
  RESTAURANTS_GET,
  RESTAURANTS_GET_SUCCESS,
  RESTAURANTS_GET_ERROR,
  MESSAGE_ADD,
  MESSAGE_CLEAR,
}
