const LOCATION_CHANGE = '@@router/LOCATION_CHANGE'

const USER_REGISTER = 'USER_REGISTER'
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export { LOCATION_CHANGE, USER_REGISTER, USER_REGISTER_SUCCESS, USER_REGISTER_ERROR }
